api:
  repository: ghcr.io/mikhail-chirkov/goracles-api
  tag: latest
  port: 80
  containerPort: 8080
  imagePullPolicy: Always

bot:
  repository: ghcr.io/mikhail-chirkov/goracles-bot
  tag: latest
  imagePullPolicy: Always

secretName: goracles-env
