apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.repository }}:{{ .Values.api.tag }}"
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          
          

