apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bot
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.bot.repository }}:{{ .Values.bot.tag }}"
          imagePullPolicy: {{ .Values.bot.imagePullPolicy }}
          volumeMounts:
          - name: bot-volume
            mountPath: /data
          env:
            - name: API_URL
              value: "http://{{ .Release.Name }}-api:{{ .Values.api.port }}"
            - name: DATABASE_PATH
              value: "/data/bot.sqlite"
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
      volumes:
        - name: bot-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc